#!/bin/bash
#
##############################################################################
#                                                                            #
#                        WPSD MMDVM HS_HAT Reset Tool                        #
#                                                                            #
##############################################################################
#
if [ "$(id -u)" != "0" ]; then
  echo -e "You need to be root to run this command...\n"
  exit 1
fi

# Special Pi4/5 handling...
# Detect Pi4/5 Hardware
if [ "$(/usr/local/sbin/.wpsd-platform-detect | grep "Pi 4 Model" | wc -l)" -ge 1 ]; then
  model="Pi4"
elif [ "$(/usr/local/sbin/.wpsd-platform-detect | grep "Pi 5 Model" | wc -l)" -ge 1 ]; then
  model="Pi5"
else
  model=""
fi
# Make the "boot" option only work on Pi 4/5 hardware, due to GPIO changes in the boards.
# The "boot" arg. leaves mmdvmhost services alone since they have not started yet and we
# need the pi4/5 GPIO pins to init before MMDVMHost. No "boot" option is for when MMDVMhost
# is started/running after bootup
if [ "${1}" = "boot" ]; then
  if [ "${model}" != "Pi4" ] && [ "${model}" != "Pi5" ]; then
    echo "The 'boot' option only works with Pi 4 and Pi 5 boards. Try again without the 'boot' option."
    exit 1
  fi
fi

if [ -f '/etc/dstar-radio.mmdvmhost' ]; then
    modemSelected=$(grep 'Hardware=' /etc/dstar-radio.mmdvmhost)
    modemSelected=${modemSelected#*=}

    # Get the user-friendly version of the selected Modem.
    modemSelectedHuman=$(grep value=\"${modemSelected}\" /var/www/dashboard/admin/configure.php | head -n 1)
    modemSelectedHuman=${modemSelectedHuman#*\">}
    modemSelectedHuman=${modemSelectedHuman::-9}

    # Replace "&amp;" with "&" in modemSelectedHuman
    modemSelectedHuman=$(echo "$modemSelectedHuman" | sed 's/&amp;/\&/g')
fi

# Get the Port the modem is on
modemPort=$(sed -n '/^\[Modem\]/,/^\[/p' /etc/mmdvmhost | grep ^"UARTPort" | awk -F '=' '{print $2}')
if [ -z "${modemPort}" ]; then
  modemPort=$(sed -n '/^\[Modem\]/,/^\[/p' /etc/mmdvmhost | grep ^"Port" | awk -F '=' '{print $2}')
fi
if [ -z "${modemPort}" ] || [ "${modemPort}" != "/dev/ttyAMA0" ]; then
  echo -e "Your Modem is not connected to the GPIO"
  exit 0
fi

# If there are no arguments (like "boot") then stop the service...
if [ -z "${1}" ]; then
  echo -e "Resetting Modem: ${modemSelectedHuman}"
  systemctl stop mmdvmhost.timer
  systemctl stop mmdvmhost.service
fi

# gpio front/back compat. for pi5 and older Pi SBCs; since Pi5 has its own GPIO chip (gpiochip4 [pinctrl-rp1])
getGPIOpinMaps=$(ls -al /sys/class/gpio/gpiochip* | sed -n "s/.*gpiochip\([0-9]*\).*/\1/p" | head -n 1)
pin20=$((getGPIOpinMaps + 20))
pin21=$((getGPIOpinMaps + 21))
# Perform modem reset...
echo ${pin20} > /sys/class/gpio/export
echo ${pin21} > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio${pin20}/direction
echo out > /sys/class/gpio/gpio${pin21}/direction
sleep 0.5
echo 0 > /sys/class/gpio/gpio${pin20}/value
echo 0 > /sys/class/gpio/gpio${pin21}/value
echo 1 > /sys/class/gpio/gpio${pin21}/value
sleep 1
echo 0 > /sys/class/gpio/gpio${pin20}/value
echo 1 > /sys/class/gpio/gpio${pin20}/value
echo 0 > /sys/class/gpio/gpio${pin20}/value
sleep 0.5
echo ${pin20} > /sys/class/gpio/unexport
echo ${pin21} > /sys/class/gpio/unexport
sleep 2

# If there are no arguments (like "boot") then start the service...
if [ -z "${1}" ]; then
  systemctl start mmdvmhost.service
  systemctl start mmdvmhost.timer
  echo -e ${message}
fi

exit 0
