#!/bin/bash

source /usr/local/sbin/.wpsd-common-funcs

UUID=$( grep UUID /etc/pistar-release | awk '{print $3}' )
platInfo=$( /usr/local/sbin/.wpsd-platform-detect )

function DisplayRepoStatus() {
    dir="$1"

    case $1 in
	"/var/www/dashboard")
	    TARGET="WPSD Digital Voice Dashboard Software"
	    ;;
	"/usr/local/sbin")
	    TARGET="WPSD Support Utilites and Programs"
	    ;;
	"/usr/local/bin")
	    TARGET="WPSD Digital Voice and Related Binaries"
	    ;;
	"/opt/cast")
	    TARGET="WPSD DVMega Cast Software"
	    ;;
    esac

    repo=$(git --work-tree=${dir} --git-dir=${dir}/.git config --get remote.origin.url)
    branch=$(git --work-tree=${dir} --git-dir=${dir}/.git symbolic-ref --short HEAD)
    ver_cmd=$( git --work-tree=${dir} --git-dir=${dir}/.git rev-parse HEAD | tail -1 | awk '{ print substr($1,1,10) }' ) # last pipe to awk: converts long hash to 10 chars.
    if [ "${branch}" != "master" ] ; then
        echo -e "  ${BULL} $TARGET:\n      On the '${BOLD}${branch}${COL_NC}' branch; Ver. # ${COL_LIGHT_ORANGE}${ver_cmd}${COL_NC}"
    else
        echo -e "  ${BULL} $TARGET:\n      Ver. # ${COL_LIGHT_ORANGE}${ver_cmd}${COL_NC}"
    fi
}

function DisplayStatus() {
    clear
    echo -e -n "${COL_LIGHT_CYAN}${BOLD}"
echo ' _      _____  _______ 
| | /| / / _ \/ __/ _ \
| |/ |/ / ___/\ \/ // /
|__/|__/_/  /___/____/'
    echo -e "\n${COL_NC}Version Status"
    echo -e "---------------"
    DisplayRepoStatus "/var/www/dashboard"
    DisplayRepoStatus "/usr/local/sbin"
    DisplayRepoStatus "/usr/local/bin"
    # dvmega cast-specific stuff
    castResult=$(isDVmegaCast)
    if [ "$castResult" == "true" ]; then
	DisplayRepoStatus "/opt/cast"
    fi
    if [ -t 1 ] || [ -n "$PS1" ] ; then # since this is called by `motdgen`, omit the following for the motd...
	echo -e "\n${COL_NC}Environment Status"
	echo -e "------------------"
	echo -e "  ${BULL} WPSD Instance ID:\n      ${COL_LIGHT_MAGENTA}${UUID}${COL_NC}"
 	echo -e "  ${BULL} Platform Info:\n      ${COL_LIGHT_MAGENTA}${platInfo}${COL_NC}"
	echo -e ""
    fi
}

DisplayStatus

exit 0
